name: Build and Package

on:
  push:
    branches:
      - branchAutomake

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential automake autoconf

    - name: Generate build files
      run: |
        aclocal
        autoconf
        automake --add-missing

    - name: Configure the project
      run: ./configure

    - name: Build the project
      run: make

    - name: Create tarball
      run: make dist

